# fly.toml app configuration file generated for beverage-personal-website on 2025-07-07T00:05:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beverage-personal-website'
primary_region = 'cdg'

[build]
  [build.args]
    GITHUB_PROFILE_URL = "https://github.com/beverage"
    LINKEDIN_PROFILE_URL = "https://linkedin.com/in/beverage"
    INSTAGRAM_PROFILE_URL = "https://instagram.com/mrbeverage"
    CONTACT_EMAIL_ADDRESS = "test@example.com"
    CV_URL = "/cv/alex-beverage-cv.pdf"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
